# Generated by Django 5.0.6 on 2024-07-03 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(max_length=255)),
                ('position_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_link', models.URLField()),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Remote', 'Remote'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Temporary', 'Temporary'), ('Volunteer', 'Volunteer'), ('Apprenticeship', 'Apprenticeship'), ('Seasonal', 'Seasonal'), ('Co-op', 'Co-op')], max_length=20)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Applied', 'Applied'), ('Unsuccessful', 'Unsuccessful'), ('Interview', 'Interview'), ('Under Consideration', 'Under Consideration'), ('Offered', 'Offered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Awaiting Response', 'Awaiting Response'), ('Follow-up Required', 'Follow-up Required'), ('Hired', 'Hired'), ('Closed', 'Closed')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('scheduled_interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_team', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=255, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('application_method', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('application_source', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_used', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_letter_used', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('application_status_history', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobtracker.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobtracker.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('reminder_timing', models.CharField(default='1 day before', max_length=50)),
                ('job_application_updates', models.BooleanField(default=True)),
                ('interview_reminders', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
